# Changes here will be overwritten by Copier
_commit: v0.1.0
_src_path: gh:xonsh/xontrib-template
email: es.bugzilla@gmail.com
enable_autoloading: true
enable_pre_commit_hooks: true
full_name: Evgeny
github_username: eugenesvk
has_aliases: true
has_events: true
package_manager: poetry
project_name: mise
project_package_name: mise
project_repo_name: xontrib-mise
project_short_description: Initializes mise (polyglot asdf-like runtime manager)
pure_py: true
py_module_name: xontrib_mise
version: 0.0.1

